micronaut:
  application:
    name: store
  server:
    port: 8080
  http:
    client:
      exception-on-error-status: false
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:thisisaverylongsecretforjwtgeneration}"'
              refresh-token:
                secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  serde:
    maximum-nesting-depth: 100
redis:
  uri: redis://localhost

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-product`}
      user: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:secret}
      schemas: mn
      default-schema: mn
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-product`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:secret}
    driverClassName: org.postgresql.Driver
    schema-generate: None
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update

